image:
  file: .gitpod.Dockerfile
tasks:
  - name: Dev
#    init: pnpm install
#    command: pnpm run dev
vscode:
  extensions:
    - vivaxy.vscode-conventional-commits
    - tabnine.tabnine-vscode
    - sonarsource.sonarlint-vscode
    - bradlc.vscode-tailwindcss
    - lokalise.i18n-ally
    - jock.svg
    - heybourn.headwind
    - GitLab.gitlab-workflow
ports:
  - name: Develope
    description: Next/Gatsby dev server
    port: 3000
    onOpen: open-preview
  - name: TabNine
    description: TabNine GUI
    port: 5555
    onOpen: ignore
